// flow-typed signature: 96c2ac1d379cf67f3df7c3a48612596e
// flow-typed version: <<STUB>>/rollup-plugin-scss_v^1.0.2/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-scss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-scss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-scss/index.cjs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-scss/index.es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-scss/index.cjs.js' {
  declare module.exports: $Exports<'rollup-plugin-scss/index.cjs'>;
}
declare module 'rollup-plugin-scss/index.es.js' {
  declare module.exports: $Exports<'rollup-plugin-scss/index.es'>;
}
