// flow-typed signature: 1e6f0960494ae0ebd2b1eb44f869d2c6
// flow-typed version: <<STUB>>/@svgr/rollup_v^2.4.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@svgr/rollup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@svgr/rollup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@svgr/rollup/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@svgr/rollup/lib/index.js' {
  declare module.exports: $Exports<'@svgr/rollup/lib/index'>;
}
